language: ruby
rvm:
- 2.5.1
script:
- bundle exec rspec spec/
before_install:
- gem update --system
- gem install bundler
after_script:
  - bundle exec rake coveralls:push
env:
  - CODECOV_TOKEN = 437fc80c-9262-4f77-9634-245c534306bb
