language: ruby
rvm:
 - 2.5.1

script:
- bundle exec rspec spec/
before_install:
- gem update --system
- gem install bundler
deploy:
  provider: heroku
  api_key:
    secure:
  on:
    repo: kiedunne/roman-numeral-converter
